#!/bin/bash
export _cachy_config="true"
export _cpusched="bore"
export _tune_bore="true"
export _NUMAdisable="true"
# run the following to only compile USED kernel modules
# modprobed-db store
export _localmodcfg="true"
export _cc_harder="true"
export _nr_cpus=8
# empty strings disable
export _per_gov=""
export _zstd_compression="true"
export _zstd_level_value="ultra"
# this enalbes clang must be set to full, thin, or none
#export _use_llvm_lto="full"
export _use_llvm_lto="none"
export _build_zfs=""
export _bcachefs=""
