general.import = [
  "~/.config/alacritty/Monokai.toml",
  "~/.config/alacritty/env.toml",
]

[font]
size = 10.0
normal = { family = "BlexMono Nerd Font", style = "SemiBold" }

[cursor]
style = { shape = "Underline", blinking = "Always" }

[window]
dynamic_title = true
opacity = 0.7
decorations_theme_variant = "Dark"
title = "Alacritty"
  
[window.dimensions]
columns = 80
lines = 24
